apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "clickhouse.name" . }}
  ports:
    - name: tcp
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: 30000
